Repository smash-teams/smash-teams-FE, pull requests merged in 2023-05, with the labels that each got.

#19 feat: 공통컴포넌트 및 추가 세팅 작업
  .gitignore
  index.html
  package.json
  public/noprofile.png
  public/redbox-logo.png
  public/title-logo.png
  src/App.tsx
  src/components/common/header/index.tsx
  src/components/common/header/style.ts
  src/components/common/layout/index.tsx
  src/components/common/layout/style.ts
  src/components/common/navbar/index.tsx
  src/components/common/navbar/style.ts
  src/components/common/profilebar/index.tsx
  src/components/common/profilebar/style.ts
  src/components/common/sidebar/index.tsx
  src/components/common/sidebar/style.ts
  src/main.tsx
  src/pages/adminPage/index.tsx
  src/pages/adminPage/style.ts
  src/pages/dayoffPage/index.tsx
  src/pages/dayoffPage/style.ts
  src/pages/historyPage/index.tsx
  src/pages/historyPage/style.ts
  src/pages/homePage/index.tsx
  src/pages/homePage/style.ts
  src/pages/loginPage/index.tsx
  src/pages/loginPage/style.ts
  src/pages/managePage/index.tsx
  src/pages/managePage/style.ts
  src/pages/nightsheetPage/index.tsx
  src/pages/nightsheetPage/style.ts
  src/pages/profilePage/index.tsx
  src/pages/profilePage/style.ts
  src/pages/registerPage/index.tsx
  src/pages/registerPage/style.ts
  src/routes/Router.tsx
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: enhancement

#20 style: 폰트 설정 수정
  index.html
  src/styles/GlobalStyles.ts
Labels: enhancement

#22 feat: Theme사용을 위한 ThemeProvider활용
  src/App.tsx
  src/styles/Theme.ts
Labels: enhancement

#24 style: 공통 컴포넌트 스타일 수정
  src/components/common/header/index.tsx
  src/components/common/header/style.ts
  src/components/common/navbar/style.ts
  src/components/common/profilebar/style.ts
  src/components/common/sidebar/style.ts
Labels: enhancement

#28 feat: msw 더미데이터 생성 및 api로직 구현
  public/mockServiceWorker.js
  src/apis/axios.ts
  src/apis/interface/Auth.ts
  src/apis/services/Auth.ts
  src/apis/services/Manage.ts
  src/apis/services/Schedule.ts
  src/mocks/adminPermissions.json
  src/mocks/adminUserList.json
  src/mocks/browsers.ts
  src/mocks/handlers.ts
  src/mocks/loginInfo.json
  src/mocks/logout.json
  src/mocks/main.json
  src/mocks/mySchedule.json
  src/mocks/superSchedule.json
  src/mocks/teamList.json
  src/mocks/userdelete.json
  src/mocks/users.json
  src/utils/cookies.ts
Labels: enhancement

#39 feat: 로그인 후 엑세스토큰 세팅
  package.json
  src/apis/axios.ts
  src/apis/interface/Auth.ts
  src/apis/services/Auth.ts
  src/components/loginForm/index.tsx
  src/components/loginForm/style.ts
  src/mocks/handlers.ts
  src/pages/loginPage/index.tsx
  src/pages/loginPage/style.ts
Labels: enhancement

#41 feat: 회원가입 페이지 로직, ux/ui 수정 작업
  src/apis/interface/Auth.ts
  src/apis/services/Auth.ts
  src/components/registerForm/index.tsx
  src/components/registerForm/style.ts
  src/pages/loginPage/style.ts
  src/pages/profilePage/index.tsx
  src/pages/registerPage/index.tsx
  src/pages/registerPage/style.ts
Labels: enhancement

#45 fix: 연차, 반차, 당직 페이지 UI및 로직 추가
  src/apis/services/Schedule.ts
  src/components/common/navbar/index.tsx
  src/components/miniCalendar/index.tsx
  src/components/miniCalendar/style.css
  src/components/miniCalendar/theme.ts
  src/components/shiftFormContainer/index.tsx
  src/components/shiftFormContainer/style.ts
  src/interface/schedule.ts
  src/pages/dayoffPage/index.tsx
  src/pages/dayoffPage/style.ts
  src/pages/nightsheetPage/index.tsx
  src/pages/nightsheetPage/style.ts
  src/routes/Router.tsx
Labels: enhancement

#49 feat: 연반차, 당직 페이지 로직 수정 1차
  src/apis/services/Schedule.ts
  src/components/common/navbar/index.tsx
  src/components/miniCalendar/index.tsx
  src/components/miniCalendar/style.css
  src/components/miniCalendar/theme.ts
  src/components/shiftFormContainer/index.tsx
  src/components/shiftFormContainer/style.ts
  src/interface/schedule.ts
  src/pages/dayoffPage/index.tsx
  src/pages/homePage/index.tsx
  src/pages/homePage/styles.css
  src/pages/homePage/styles.scss
Labels: enhancement

#50 feat: 필터링 기능 구현 및 팀에 따라 연차 정보에 따라 레이아웃 다르게 보이도록 구현
  src/components/userInfo/userInfoContainer/index.tsx
  src/components/userInfo/userInfoItem/index.tsx
  src/interface/main.ts
  src/interface/schedule.ts
  src/pages/homePage/index.tsx
  src/pages/homePage/style.ts
  src/pages/homePage/styles.scss
  src/utils/calendarTheme.ts
Labels: enhancement

#51 fix: 남은연차 카운팅, 연차/반차 표시버튼 스타일 수정
  src/components/shiftFormContainer/index.tsx
  src/components/shiftFormContainer/style.ts
Labels: enhancement

#52 fix: 파일 이동 및 ts 에러 해결
  src/interface/schedule.ts
  src/pages/homePage/index.tsx
  src/utils/ExcelDownload.tsx
Labels: enhancement

#53 fix: Type Error 해결
  src/apis/services/Schedule.ts
  src/components/shiftFormContainer/index.tsx
  src/pages/dayoffPage/index.tsx
Labels: enhancement

#56 feat: 내역, 관리 페이지 로직 정리 및 개인정보수정, 회원탈퇴 로직 구현
  package.json
  src/apis/interface/Auth.ts
  src/apis/services/Auth.ts
  src/apis/services/Schedule.ts
  src/components/HalfOffShiftForm/index.tsx
  src/components/HistoryCard/index.tsx
  src/components/common/SwiperList/index.tsx
  src/components/common/completeItem/style.ts
  src/components/common/header/index.tsx
  src/components/common/header/style.ts
  src/components/common/navbar/index.tsx
  src/components/common/profilebar/index.tsx
  src/components/common/profilebar/style.ts
  src/components/deleteButton/index.tsx
  src/components/deleteButton/style.ts
  src/components/loginForm/style.ts
  src/components/profileForm/index.tsx
  src/components/profileForm/style.ts
  src/components/registerForm/index.tsx
  src/components/registerForm/style.ts
  src/interface/component.ts
  src/pages/historyPage/index.tsx
  src/pages/managePage/index.tsx
  src/pages/profilePage/index.tsx
  src/pages/registerPage/index.tsx
  src/pages/registerPage/style.ts
  src/routes/ProtectedRouter.tsx
  yarn.lock
Labels: enhancement

#57 fix: 당직데이터 에러 해결 및 주석제거
  src/components/shiftFormContainer/index.tsx
Labels: bug, enhancement

#58 feat: 배포 전 타입에러 정리
  src/App.tsx
  src/apis/services/Schedule.ts
  src/components/HalfOffShiftForm/index.tsx
  src/components/common/SwiperList/index.tsx
  src/components/common/completeItem/index.tsx
  src/components/miniCalendar/index.tsx
  src/components/shiftFormContainer/index.tsx
  src/interface/schedule.ts
  src/mocks/browsers.ts
  src/mocks/handlers.ts
  src/pages/dayoffPage/index.tsx
  src/pages/historyPage/index.tsx
  src/pages/homePage/index.tsx
  src/pages/homePage/style.ts
Labels: enhancement

#59 fix: type 중복 선언 및 타입 수정
  src/interface/main.ts
  src/pages/homePage/index.tsx
Labels: bug

#61 fix: 파일 경로 수정
  src/components/HistoryCard/index.tsx
Labels: bug

#76 fix: 이미지 경로 변경
  src/components/userInfo/userInfoItem/index.tsx
  src/pages/homePage/index.tsx
Labels: bug

#84 fix: 캘린더 연차 적용시 나오는 프로필 수정
  src/components/miniCalendar/index.tsx
Labels: bug, enhancement

#85 feat: 스케줄 API 데이터 변경으로인한 로직 수정
  src/components/HalfOffShiftForm/index.tsx
  src/components/HistoryCard/index.tsx
  src/components/common/completeItem/index.tsx
  src/components/common/navbar/index.tsx
Labels: enhancement
